// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbookV2.proto

package org.noahsark.tutorial.protos;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Person peoples = 1;</code>
   */
  java.util.List<org.noahsark.tutorial.protos.Person> 
      getPeoplesList();
  /**
   * <code>repeated .tutorial.Person peoples = 1;</code>
   */
  org.noahsark.tutorial.protos.Person getPeoples(int index);
  /**
   * <code>repeated .tutorial.Person peoples = 1;</code>
   */
  int getPeoplesCount();
  /**
   * <code>repeated .tutorial.Person peoples = 1;</code>
   */
  java.util.List<? extends org.noahsark.tutorial.protos.PersonOrBuilder> 
      getPeoplesOrBuilderList();
  /**
   * <code>repeated .tutorial.Person peoples = 1;</code>
   */
  org.noahsark.tutorial.protos.PersonOrBuilder getPeoplesOrBuilder(
      int index);

  /**
   * <code>map&lt;string, .tutorial.Person&gt; people_map = 2;</code>
   */
  int getPeopleMapCount();
  /**
   * <code>map&lt;string, .tutorial.Person&gt; people_map = 2;</code>
   */
  boolean containsPeopleMap(
      java.lang.String key);
  /**
   * Use {@link #getPeopleMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.noahsark.tutorial.protos.Person>
  getPeopleMap();
  /**
   * <code>map&lt;string, .tutorial.Person&gt; people_map = 2;</code>
   */
  java.util.Map<java.lang.String, org.noahsark.tutorial.protos.Person>
  getPeopleMapMap();
  /**
   * <code>map&lt;string, .tutorial.Person&gt; people_map = 2;</code>
   */

  org.noahsark.tutorial.protos.Person getPeopleMapOrDefault(
      java.lang.String key,
      org.noahsark.tutorial.protos.Person defaultValue);
  /**
   * <code>map&lt;string, .tutorial.Person&gt; people_map = 2;</code>
   */

  org.noahsark.tutorial.protos.Person getPeopleMapOrThrow(
      java.lang.String key);
}
